### ISSUE TITLE
account_invoice_import dont work on 16.0

### ISSUE THREAD

**Issue by pcastelovigo** [flinq-ingenieria/odoo-extra-ports#1]
2024-12-21 01:45:27,972 98315 WARNING floc odoo.addons.openupgrade_framework.odoo_patch.odoo.addons.base.models.ir_ui_view: Can't render custom view account_invoice_import.account_journal_dashboard_kanban_view for model account.journal. Assuming you are migrating between major versions of Odoo. Please review the view contents manually after the migration.
Error: Element '<button class="btn btn-primary o_button_upload_bill oe_kanban_action_button" journal_type="purchase">' cannot be located in parent view 
2024-12-21 01:45:27,982 98315 INFO floc odoo.modules.loading: loading account_invoice_import/views/res_partner.xml 
2024-12-21 01:45:28,008 98315 WARNING floc odoo.modules.loading: Transient module states were reset 
2024-12-21 01:45:28,009 98315 ERROR floc odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/modules/loading.py", line 373, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/modules/loading.py", line 232, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/modules/loading.py", line 72, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/tools/convert.py", line 709, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /home/lolo/Escritorio/ODOO/TRABAJO/account_invoice_import/views/res_partner.xml:8
La vista heredada no puede tener 'grupos' definidos en el registro. Use los atributos de 'grupos' dentro de la definición de la vista

View error context:
'-no context-'

2024-12-21 01:45:28,012 98315 CRITICAL floc odoo.service.server: Failed to initialize database floc. 
Traceback (most recent call last):
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/service/server.py", line 1311, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/modules/loading.py", line 373, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/modules/loading.py", line 232, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/modules/loading.py", line 72, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/home/lolo/Escritorio/ODOO16/workdir/odooperp/odoo/tools/convert.py", line 709, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /home/lolo/Escritorio/ODOO/TRABAJO/account_invoice_import/views/res_partner.xml:8
La vista heredada no puede tener 'grupos' definidos en el registro. Use los atributos de 'grupos' dentro de la definición de la vista

View error context:
'-no context-'

**Comment by pcastelovigo** [comment]
fixed!
